version: '3'

services:
  solr:
    image: solr
    ports:
     - "8983:8983"
    volumes:
      - /home/rodrigo/Documentos/volume-docker/solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore