version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo
    image: mongo
    expose:
      - 27017
    volumes:
      - ./scripts:/scripts
    command: 
      - /scripts/add_user.sh
    ports:
      - 27017:27017
    restart: always
